#!/bin/sh

# create the autoconf/automake/libtool environment in the current directory

aclocal
libtoolize --force
automake -a
autoconf

if test -f bootstrap ; then
  touch common/locale.scm common/iconv.scm common/gettext.scm \
      common/bigloo-compat.scm common/readline.scm common/history.scm \
      common/termios.scm common/pthread.scm common/gc.scm common/socket.scm
fi


